-- 1. rooms 테이블 생성
CREATE TABLE public.rooms (
  id text PRIMARY KEY, -- 무작위 대문자/숫자 4자리 방 코드 (예: X7A8)
  status text NOT NULL DEFAULT 'waiting', -- 'waiting', 'playing', 'finished'
  current_tile text, -- 현재 뽑힌 타일 (예: "15", "Joker")
  turn_count integer NOT NULL DEFAULT 0, -- 진행된 턴 수 (0 ~ 20)
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. players 테이블 생성
CREATE TABLE public.players (
  id bigint GENERATED BY DEFAULT as identity PRIMARY KEY,
  room_id text NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
  name text NOT NULL,
  score integer NOT NULL DEFAULT 0,
  is_finished boolean NOT NULL DEFAULT false,
  confirmed_turn integer NOT NULL DEFAULT 0, -- 학생이 현재 턴까지 확정했는지 여부 기록 (예: 1이면 1턴 확정)
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. 테이블 실시간 복제(Realtime) 활성화
-- (Supabase DB에 따라 이미 활성화되어 있는 경우 에러가 날 수 있으니 대시보드에서 직접 체크하셔도 됩니다.)
ALTER PUBLICATION supabase_realtime ADD TABLE public.rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE public.players;

-- 4. RLS (Row Level Security) 설정
-- 로그인 없이 누구나 게임에 참여할 수 있도록 RLS를 비활성화하거나, 전체 허용 정책을 추가해야 합니다.
-- 방법 A: RLS 비활성화 (권장 - 가장 간단함)
ALTER TABLE public.rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.players DISABLE ROW LEVEL SECURITY;

-- 방법 B: RLS를 유지하면서 모든 권한 허용 (보안 정책 적용 시)
-- CREATE POLICY "Allow all rooms" ON public.rooms FOR ALL TO anon USING (true) WITH CHECK (true);
-- CREATE POLICY "Allow all players" ON public.players FOR ALL TO anon USING (true) WITH CHECK (true);

